  steps:
  # Build the container image
  - name: gcr.io/cloud-builders/docker
    args: 
        - build
        - '--no-cache'
        - '-t'
        - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
        - .
        - '-f'
        - Dockerfile 
    id: Build  
  - name: gcr.io/cloud-builders/docker
    args: 
        - push
        - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'SERVICE-NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
    - '--region'
    - 'REGION'
    id: Deploy
    timeout: 1200s
  images:
  - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'